### ISSUE TITLE
Welcome to iOS Development!!

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/mpcs51030-2017-summer-forum#1]
Please leave a comment below.

**Comment by acham1** [comment]
For Assignment 1's Swift Tour, I am finding build-time errors (e.g. in the first topic 'Simple Values' the section on multi-line strings makes compiler errors). I think this is because I'm using Xcode 8.3.3 which I just got off the App Store, but this tutorial playground may include features from Swift 4. For this assignment, should I remedy this by downloading the Xcode 9 beta, or should I continue with Xcode 8.3.3 (as per the introductory e-mail) and try to find a version of the tutorial made for Swift 3? Thanks!

**Comment by tabinks** [comment]
Welcome to the world of Apple's aggressive updates schedule.  My recommendation would be to download the Xcode 9 beta and continue with the playground using that.  The changes between Swift 3 and Swift 4 in this Playground are pretty small, despite all the warning you get.

You'll notice that the tutorial uses Xcode 8 and Swift 3, so switch back for this part of the assignment.

**Comment by xuefeng11** [comment]
Do we use piazza? or we only use github issue to discuss? 
thanks

**Comment by tabinks** [comment]
We will be using Github.

**Comment by Gloria-Xiaolu-Zhang** [comment]
This discussion is helpful. Thanks guys!

To further clarify two things about hw1:
1. The hw we need to submit will be an updated version of this Swift Guided Tour Playground. We update it mainly based on what "Experiment" sections in the playground asks us to do. Right?
2. Do we need to submit the work of FoodTracker? I.e.  the Start Developing iOS Apps (Swift) tutorial.

Thanks!

**Comment by tabinks** [comment]
Yes.  You should be submitting the Food Tracker app as well.  

The playground you download will have all of the code. The idea is just to show some evidence that you played around with it. There are no specific requirements for changes you're making to the playground.

**Comment by Gloria-Xiaolu-Zhang** [comment]
I see. Thank you Andrew!

**Comment by cassamanojc** [comment]
> Remember that all students can see these issues, so anything personal should be sent directly to the instructors.

Does "so anything personal should be sent directly to the instructors" mean to create an issue in our own repository (the one used to submit the homework) and then assign it to one of the instructors?

**Comment by tabinks** [comment]
No, you can send us email.  I'll go over in more detail on Tuesday.
